Fix require statement to use correct name
The associated files in the Avatax_TaxService gem are "avatax_taxservice.rb" and "avatax_addressservice.rb".

On case-insensitive file systems like OSX you can still do `require 'Avatax_TaxService'.
But on case-*sensitive* file systems like Ubuntu the require will fail with something like:

    LoadError: cannot load such file -- Avatax_TaxService

or:

    `require': No such file to load -- Avatax_TaxService (LoadError)